name: Package

on:
  workflow_dispatch:

defaults:
  run:
    shell: 'bash -Eeuo pipefail -x {0}'

jobs:

  package:
    name: Package
    runs-on: ubi-9
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install make and rpmbuild
        run: |
          dnf install -y make rpmdevtools 

      - name: Build Package
        run: |
          spectool -g -R quarkus.spec
          rpmbuild -bb --clean quarkus.spec