name: Package

on:
  workflow_dispatch:

defaults:
  run:
    shell: 'bash -Eeuo pipefail -x {0}'

jobs:

  package:
    name: Package
    runs-on: almalinux-9
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install make and rpmbuild
        run: |
          sudo dnf install -y make rpm-build

      - name: Build RPM package
        run: |
          make rpm