name: Release

on:
  workflow_dispatch:

defaults:
  run:
    shell: 'bash -Eeuo pipefail -x {0}'

jobs:

  package:
    name: Package
    runs-on: ubi-9
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install make and rpmbuild
        run: |
          dnf install -y make rpmdevtools 

      - name: Build Package
        run: |
          spectool -g -R quarkus.spec
          rpmbuild -bb --clean quarkus.spec

      - name: Upload Package
        run: |
          curl --user $GITEA_USERNAME:$GITEA_TOKEN \
          --upload-file /opt/app-root/src/rpmbuild/RPMS/noarch/quarkus-*.noarch.rpm \
          ${{ vars.INSTANCE }}/api/packages/${{ github.repository_owner }}/rpm/upload
        env:
          GITEA_USERNAME: ${{ github.repository_owner }}
          GITEA_TOKEN: ${{ secrets.REGISTRY_TOKEN }}
        